version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  # BLedger:
  #   image: BLedger:latest
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - .env
volumes:
  db:
    driver: local
  cache:
    driver: local
